output_dir: ablation_stage_1_post_single_example_local
logging_dir: logs
seed: 44

report_to:
  tracker_name: Wan-Train
  wandb_name: ablation_stage_1_post_single_example
  report_to: wandb

data_config:
  use_shuffle: true
  pin_memory: true
  persistent_workers: false
  force_rebuild: true
  single_res: true
  single_height: 384
  single_width: 640
  dataloader_num_workers: 2
  prefetch_factor: 2
  caption_dropout_p: 0
  id_token: ""
  instance_data_root:
    - "/root/autodl-tmp/Selector_VLM/example/out_latents"
  use_stage1_dataset: true

model_config:
  pretrained_model_name_or_path: "/root/autodl-fs/BestWishYSH/Helios-Base"
  transformer_model_name_or_path: "/root/autodl-fs/BestWishYSH/Helios-Base"
  subfolder: "transformer_init"
  load_checkpoints_custom: false
  load_dcp: false
  upcast_vae: true
  enable_slicing: false
  enable_tiling: false
  lora_rank: 128
  lora_alpha: 128.0
  lora_dropout: 0.0
  lora_layers: "all-linear"
  lora_exclude_modules:
    - down
    - up
  train_norm_layers: false

validation_config:
  validation_steps: 1000000000
  validation_height: 384
  validation_width: 640
  validation_max_num_frames: 99
  validation_prompts:
    - "smoke test"
  validation_guidance_scale: 5.0
  validation_latent_window_size:
    - 9
  validation_stream_chunk_size:
    - 1
  num_validation_videos: 1
  num_inference_steps: 10
  use_kv_cache: false

training_config:
  allow_tf32: false
  gradient_checkpointing: true
  enable_xformers_memory_efficient_attention: false
  enable_npu_flash_attention: false
  upcast_before_saving: false
  offload: false
  mixed_precision: "bf16"
  max_train_steps: 1
  train_batch_size: 1
  gradient_accumulation_steps: 1
  checkpointing_steps: 1
  resume_from_checkpoint: null
  save_checkpoints_custom: false
  learning_rate: 3e-5
  lr_scheduler: "constant"
  lr_warmup_steps: 0
  optimizer: "adamw"
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-04
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  weighting_scheme: "logit_normal"
  logit_mean: 0.0
  logit_std: 1.0
  mode_scale: 1.29
  use_dynamic_shifting: false
  base_seq_len: 256
  max_seq_len: 4096
  base_shift: 0.5
  max_shift: 1.15
  vae_decode_type: "default"
  use_ema: false
  use_ema_validation: false
  ema_decay: 0.999
  ema_start_step: 250
  ema_zero3_port: 10543
  ema_deepspeed_config_file: "scripts/accelerate_configs/zero3.json"
  is_enable_stage1: true
  history_sizes:
    - 16
    - 2
    - 1
  latent_window_size:
    - 9
  is_random_drop: true
  random_drop_v2v_ratio: 0.4
  random_drop_t2v_ratio: 0.4
  corrupt_model_input: false
  corrupt_mode_model_input: "noise"
  corrupt_mode_prob_model_input: 0.9
  is_frame_independent_corrupt_model_input: true
  is_chunk_independent_corrupt_model_input: false
  noise_corrupt_ratio_model_input: 0.33333333333333
  noise_corrupt_clean_prob_model_input: 0.1
  downsample_min_corrupt_ratio_model_input: 0.9
  downsample_max_corrupt_ratio_model_input: 1.0
  corrupt_history: true
  corrupt_mode_history: "noise"
  corrupt_mode_prob_history: 0.9
  is_frame_independent_corrupt_history: true
  is_chunk_independent_corrupt_history: false
  noise_corrupt_ratio_history_short: 0.33333333333333
  noise_corrupt_ratio_history_mid: 0.33333333333333
  noise_corrupt_ratio_history_long: 0.33333333333333
  noise_corrupt_clean_prob_history: 0.1
  downsample_min_corrupt_ratio_history: 0.9
  downsample_max_corrupt_ratio_history: 1.0
  is_amplify_history: false
  history_scale_mode: "per_head"
  is_train_full_patch_embedding: false
  is_train_lora_patch_embedding: true
  has_multi_term_memory_patch: true
  is_train_full_clean_patch_embedding: true
  is_train_lora_clean_patch_embedding: false
  zero_history_timestep: true
  guidance_cross_attn: true
  restrict_self_attn: false
  is_train_restrict_lora: false
  restrict_lora: false
  restrict_lora_rank: 128

