output_dir: /root/autodl-fs/output/v3_selector_v2_try_2026_03_31_0114
logging_dir: /root/autodl-fs/output/v3_selector_v2_try_2026_03_31_0114/logs
seed: 43


report_to:
  tracker_name: Wan-Train
  wandb_name: /root/autodl-fs/output/v3_selector_v2_try_2026_03_31_0114
  report_to: wandb


data_config:
  # ---- Base ----
  use_shuffle: true
  pin_memory: true
  persistent_workers: true
  force_rebuild: true
  single_res: true
  single_height: 384
  single_width: 640
  dataloader_num_workers: 8
  prefetch_factor: 2
  caption_dropout_p: 0
  id_token: ""
  instance_data_root:
    - "/root/autodl-tmp/Helios/example/toy_data/latents_long"
  # ---- Stage 1 ----
  use_stage1_dataset: true


model_config:
  # ---- Path ----
  pretrained_model_name_or_path: "/root/autodl-fs/BestWishYSH/HeliosDistillede"
  transformer_model_name_or_path: "/root/autodl-fs/Wan-AI/Wan2.1-T2V-14B-Diffusers"
  load_checkpoints_custom: false
  load_dcp: false
  # ---- Vae ----
  upcast_vae: true
  enable_slicing: false
  enable_tiling: false
  # ---- Lora ----
  lora_rank: 128
  lora_alpha: 128.0
  lora_dropout: 0.0
  lora_layers: "all-linear"
  lora_exclude_modules:
    - down
    - up
  # ---- Other ----
  train_norm_layers: false


validation_config:
  validation_steps: 500
  validation_height: 384
  validation_width: 640
  validation_max_num_frames: 99
  validation_prompts:
    - "An old man in blue jeans and a white T-shirt takes a leisurely stroll along a bustling street in Mumbai, India, during a breathtaking sunset. He walks with a gentle sway, his weathered face reflecting the warm hues of the setting sun. His hands rest casually in his pockets, and he appears content and at peace. The background features a vibrant mix of colorful buildings, street vendors, and pedestrians, with the sky painted in shades of orange, pink, and purple. The photo has a nostalgic and documentary style, capturing the essence of a serene moment amidst the city's energy. Suddenly, his gray-haired Indian friend, dressed in a plaid shirt and black pants, greets him warmly; the old man responds eagerly and they shake hands heartily. The camera slowly orbits 360 degrees around the two main characters smoothly and gently, maintaining a medium shot with soft focus on them throughout the rotation."
    #- "An old man in blue jeans and a white T-shirt takes a leisurely stroll along a bustling street in Mumbai, India, during a breathtaking sunset. He walks with a gentle sway, his weathered face reflecting the warm hues of the setting sun. His hands rest casually in his pockets, and he appears content and at peace. The background features a vibrant mix of colorful buildings, street vendors, and pedestrians, with the sky painted in shades of orange, pink, and purple. The photo has a nostalgic and documentary style, capturing the essence of a serene moment amidst the city's energy.The camera slowly orbits 360 degrees around the main character smoothly and gently, maintaining a medium shot with soft focus on the old man throughout the rotation."
  validation_guidance_scale: 5.0
  validation_latent_window_size:
    - 9
  num_validation_videos: 1
  num_inference_steps: 50


training_config:
  # ---- Environment ----
  allow_tf32: false
  gradient_checkpointing: true
  enable_xformers_memory_efficient_attention: false
  enable_npu_flash_attention: false
  upcast_before_saving: false
  offload: false
  mixed_precision: "bf16"
  # ---- Training Resource ----
  max_train_steps: 100000
  train_batch_size: 1
  gradient_accumulation_steps: 1
  checkpointing_steps: 500
  resume_from_checkpoint: "latest"
  save_checkpoints_custom: false
  # ---- Optimizer ----
  learning_rate: 5e-5
  lr_scheduler: "constant"
  lr_warmup_steps: 250
  optimizer: "adamw"
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-04
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  weighting_scheme: "logit_normal"
  logit_mean: 0.0
  logit_std: 1.0
  mode_scale: 1.29
  # ---- Dynamic Shifting Parameters ----
  use_dynamic_shifting: false
  base_seq_len: 256
  max_seq_len: 4096
  base_shift: 0.5
  max_shift: 1.15
  # ---- VAE Decode Parameters ----
  vae_decode_type: "default"
  # ---- EMA Parameters ----
  use_ema: false
  use_ema_validation: false
  ema_decay: 0.999
  ema_start_step: 250
  ema_zero3_port: 10543
  ema_deepspeed_config_file: "scripts/accelerate_configs/zero3.json"
  # ---- Stage 1 Parameters ----
  is_enable_stage1: true
  history_sizes:
    - 16
    - 2
    - 1
  latent_window_size:
    - 9
  is_random_drop: true
  random_drop_v2v_ratio: 0.4
  random_drop_t2v_ratio: 0.4
  #
  corrupt_model_input: false
  corrupt_mode_model_input: "noise"
  corrupt_mode_prob_model_input: 0.9
  is_frame_independent_corrupt_model_input: true
  is_chunk_independent_corrupt_model_input: false
  noise_corrupt_ratio_model_input: 0.33333333333333
  noise_corrupt_clean_prob_model_input: 0.1
  downsample_min_corrupt_ratio_model_input: 0.9
  downsample_max_corrupt_ratio_model_input: 1.0
  corrupt_history: true
  corrupt_mode_history: "noise"
  corrupt_mode_prob_history: 0.9
  is_frame_independent_corrupt_history: true
  is_chunk_independent_corrupt_history: false
  noise_corrupt_ratio_history_short: 0.33333333333333
  noise_corrupt_ratio_history_mid: 0.33333333333333
  noise_corrupt_ratio_history_long: 0.33333333333333
  noise_corrupt_clean_prob_history: 0.1
  downsample_min_corrupt_ratio_history: 0.9
  downsample_max_corrupt_ratio_history: 1.0
  #
  is_amplify_history: false
  history_scale_mode: "per_head"
  #
  is_train_full_patch_embedding: false
  is_train_lora_patch_embedding: true
  has_multi_term_memory_patch: true
  is_train_full_clean_patch_embedding: true
  is_train_lora_clean_patch_embedding: false
  zero_history_timestep: true
  guidance_cross_attn: true
  restrict_self_attn: false
  is_train_restrict_lora: false
  restrict_lora: false
  restrict_lora_rank: 128
  # ---- Selector Parameters ----
  use_selector: true
  selector_k_select: 4
  selector_alpha: 1.0
  selector_cross_frame_alpha: 0.85
  selector_pos_power: 1.8
  selector_pos_eta: 0.4
  selector_dropout: 0.3
