output_dir: /root/autodl-fs/output/5_26_fuxian_5
logging_dir: /root/autodl-fs/output/5_26_fuxian_5/logs
seed: 43


report_to:
  tracker_name: Wan-Train
  wandb_name: /root/autodl-fs/output/5_26_fuxian_5
  report_to: wandb


data_config:
  # ---- Base ----
  use_shuffle: true #true
  pin_memory: true
  persistent_workers: true
  force_rebuild: true
  single_res: true
  single_height: 384
  single_width: 640
  dataloader_num_workers: 8
  prefetch_factor: 2
  caption_dropout_p: 0
  id_token: ""
  instance_data_root:
  #    - "/root/autodl-tmp/Helios/data_memory_selector/apdcephfs_qy2/share_302508595/xiaodayang/seedance/seedance/video_light_change/latents_short_only"
     -  "/root/autodl-fs/HeliosBench-Weights/demo_data/one-only"
  #  - "/root/autodl-tmp/Helios/data_memory_selector/apdcephfs_qy2/share_302508595/xiaodayang/seedance/seedance/video_light_change/latents_short"
  # ---- Stage 1 ----
  use_stage1_dataset: true


model_config:
  # ---- Path ----
  pretrained_model_name_or_path: "/root/autodl-fs/BestWishYSH/Helios-Base"
  transformer_model_name_or_path: "/root/autodl-fs/Wan-AI/Wan2.1-T2V-14B-Diffusers"
  load_checkpoints_custom: false
  # load_model_path:
  load_dcp: false
  # load_dcp_path:
  # ---- Vae ----
  upcast_vae: true
  enable_slicing: false
  enable_tiling: false
  # ---- Lora ----
  lora_rank: 128    #128
  lora_alpha: 128.0
  lora_dropout: 0.0
  lora_layers: "all-linear"
  # lora_target_modules:
  #   - to_k
  #   - to_q
  #   - to_v
  #   - to_out.0
  #   - ffn.net.0.proj
  #   - ffn.net.2
  lora_exclude_modules:
    - down
    - up
  # ---- Other ----
  train_norm_layers: false


validation_config:
  first_step_valid: true
  validation_steps: 250 #10000
  validation_height: 384
  validation_width: 640
  validation_max_num_frames: 198
  # Interactive validation (segmented prompts)
  validation_prompts:
     - "A playful interaction between two individuals, a woman and a young girl, who are seated on a bed in a cozy, well-lit room. The woman, dressed in a beige sweater and blue jeans, and the girl, wearing a gray sweater and blue jeans, are engaged in a game of rock-paper-scissors. They both make exaggerated gestures with their hands, indicating the various moves of the game. The woman's hands are raised in the air, while the girl's hands are clenched into fists. They both laugh and cheer as they play, with the woman's laughter being particularly loud and enthusiastic. The room is decorated with soft lighting and star-shaped decorations, creating a warm and inviting atmosphere. The bed they are sitting on is covered with a white blanket, and there are pillows scattered around them. The overall mood of the video is joyful and lighthearted, with the two individuals clearly enjoying their time together."
  #  - "A skateboarder in a white t-shirt with a red lightning bolt walks down a suburban street, holding his board as the sun casts long shadows."
  #  - "The skateboarder walks into a graffiti-covered tunnel, his shadow stretching on the concrete walls as he moves deeper into the dim space."
  #  - "Emerging from the tunnel, the skateboarder rides his board out into the bright daylight, silhouetted against the open sky."
  # use_interpolate_prompt: false
  # interpolation_steps: 1
  # interpolate_time_list: [2, 3, 4]  # must satisfy min(interpolate_time_list) > interpolation_steps
  validation_guidance_scale: 5 #5
  validation_latent_window_size:
    - 9
  num_validation_videos: 1
  num_inference_steps: 50


training_config:
  # ---- Environment ----
  allow_tf32: false
  gradient_checkpointing: true
  enable_xformers_memory_efficient_attention: false
  enable_npu_flash_attention: false
  upcast_before_saving: false
  offload: false
  mixed_precision: "bf16"
  # ---- Training Resource ----
  max_train_steps: 100000  #100000
  train_batch_size: 1  #16
  gradient_accumulation_steps: 1
  checkpointing_steps: 500  #500
  resume_from_checkpoint: "latest"
  save_checkpoints_custom: false
  # ---- Optimizer ----
  learning_rate: 5e-5
  lr_scheduler: "constant"
  lr_warmup_steps: 500  #250
  optimizer: "adamw"
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-04
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  weighting_scheme: "logit_normal"  # ["sigma_sqrt", "logit_normal", "mode", "cosmap", "none"]
  logit_mean: 0.0
  logit_std: 1.0
  mode_scale: 1.29
  # ---- Dynamic Shifting Parameters ----
  use_dynamic_shifting: false
  base_seq_len: 256
  max_seq_len: 4096
  base_shift: 0.5
  max_shift: 1.15
  # ---- VAE Decode Parameters ----
  vae_decode_type: "default"
  # ---- EMA Parameters ----
  use_ema: false
  use_ema_validation: false
  ema_decay: 0.999
  ema_start_step: 250
  ema_zero3_port: 10543
  ema_deepspeed_config_file: "scripts/accelerate_configs/zero3.json"
  # ---- Stage 1 Parameters ----
  is_enable_stage1: true
  history_sizes:
    - 16
    - 2
    - 1
  latent_window_size:
    # - 12
    # - 10
    - 9
    # - 8
    # - 6
    # - 5
    # - 4
    # - 3
    # - 2
    # - 1
  is_random_drop: true #true
  random_drop_v2v_ratio: 0.4
  random_drop_t2v_ratio: 0.4
  # 
  corrupt_model_input: false
  corrupt_mode_model_input: "noise"
  corrupt_mode_prob_model_input: 0.9
  is_frame_independent_corrupt_model_input: true
  is_chunk_independent_corrupt_model_input: false
  noise_corrupt_ratio_model_input: 0.33333333333333
  noise_corrupt_clean_prob_model_input: 0.1
  downsample_min_corrupt_ratio_model_input: 0.9
  downsample_max_corrupt_ratio_model_input: 1.0
  corrupt_history: true
  corrupt_mode_history: "noise"
  corrupt_mode_prob_history: 0.9
  is_frame_independent_corrupt_history: true
  is_chunk_independent_corrupt_history: false
  noise_corrupt_ratio_history_short: 0.33333333333333
  noise_corrupt_ratio_history_mid: 0.33333333333333
  noise_corrupt_ratio_history_long: 0.33333333333333
  noise_corrupt_clean_prob_history: 0.1
  downsample_min_corrupt_ratio_history: 0.9
  downsample_max_corrupt_ratio_history: 1.0
  # 
  is_amplify_history: false
  history_scale_mode: "per_head"
  # 
  is_train_full_patch_embedding: false
  is_train_lora_patch_embedding: true
  has_multi_term_memory_patch: true
  is_train_full_clean_patch_embedding: true
  is_train_lora_clean_patch_embedding: false
  zero_history_timestep: true
  guidance_cross_attn: true
  restrict_self_attn: false
  is_train_restrict_lora: false
  restrict_lora: false
  restrict_lora_rank: 128